import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useGetAllUsersQuery } from '../generated/graphql';

const Home: NextPage = ({users}: any) => {
   const {data, loading, error} = useGetAllUsersQuery()
  
  if (loading) return <p>Loading...</p>;
  console.log(data)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
    </div>
  )
}

// export const getServerSideProps = async () => {
 

//   return {
//     props: {
//       users: data
//     },
//  };
// }

export default Home
